;;; monokai-dave-theme.el --- an Emacs 24 theme based on Monokai Dave (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1412595804
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Monokai Dave (tmTheme) by 
;;
;;; Code:

(deftheme monokai-dave
  "monokai-dave-theme - Created by tmtheme-to-deftheme - 2014-10-06 12:43:24 +0100")

(custom-theme-set-variables
 'monokai-dave
)

(custom-theme-set-faces
 'monokai-dave
 ;; basic theming.

 '(default ((t (:foreground "#F8F8F2" :background "#0F1110" ))))
 '(region  ((t (:background "#48a2e4" :foreground "#f8f8f2"))))
 '(cursor  ((t (:background "#F8F8F0"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#7c7d7a"  :background "#0f1110" :underline nil :weight light :inherit nil))))
 '(fringe                              ((t (                       :background "#0f1110" ))))
 '(hl-line ((t (:foreground nil :background "#202422"))))
 '(variable-pitch                      ((t (:family "Proxima Nova"))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#c1c1b2"  :background "#252725" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#eaeae5"  :background "#252725" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))
 '(show-paren-match                    ((t (:underline t :inherit nil))))


 '(diff-removed ((t (:foreground "#F92672"  ))))
 '(diff-added ((t (:foreground "#A6E22E"  ))))
 '(diff-changed ((t (:foreground "#E6DB74"  ))))
 '(font-lock-comment-face ((t (:foreground "#5D6D71" :italic t ))))
 '(font-lock-string-face ((t (:foreground "#E6DB74" :background "#252313" ))))
 '(font-lock-builtin-face ((t (:foreground "#AE81FF"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#76E3FF"  ))))
 '(font-lock-keyword-face ((t (:foreground "#F92672" :background "#2C0715" ))))
 '(font-lock-type-face ((t (:foreground "#A6E22E"  :underline t))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22E" :background "#1F2A09"))))
 '(js3-function-param-face ((t (:foreground "#FF9821" :background "#0F1110" ))))
 '(js2-function-param ((t (:foreground "#FF9821" :background "#0F1110" ))))
 '(font-lock-warning-face ((t (:foreground "#F8F8F0" :background "#AE81FF" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5D6D71"  ))))

 '(whitespace-space ((t (:foreground "#575754" :background nil))))
 '(whitespace-tab ((t (:foreground "#575754" :background nil))))
 '(whitespace-indentation ((t (:foreground "#575754" :background nil))))
 '(whitespace-newline ((t (:foreground "#575754" :background nil))))
 '(whitespace-line ((t (:foreground nil :background nil))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#7a5bb3"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#896ebb"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#9880c4"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#a792cc"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#b6a5d5"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#c5b7de"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#d4cae6"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#e3dcef"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#f2eef7"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'monokai-dave)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; monokai-dave-theme.el ends here
